assets:
  - probo.sql.gz
  - files.tar.gz
steps:
  - name: Probo site setup
    plugin: Drupal
    database: probo.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    drupalVersion: 7
    clearCaches: true
    revertFeatures: true
  - name: Set the files
    command: "cd /assets; gunzip -c /assets/files.tar.gz;"
    command: "cp /assets/files /var/www/html/sites/default/files; ls -la /var/www/html/sites/default/files"
