assets:
  - probo.sql.gz
steps:
  - name: Probo site setup
    plugin: Drupal
    database: probo.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    drupalVersion: 7
    clearCaches: true
    revertFeatures: true
  - name: Set the files
#    command: "tar xvfz /assets/files.tar.gz; cp files/ /var/www/html/sites/default/files;"
    command: "ls -la"

